<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8'); ?>
<!DOCTYPE html>
<meta charset="utf-8">
<head>
<title><?php echo $this->pagetitle ?> | Library On-line</title>
<!-- HIP generated <?php echo date("d-m-Y:Gi", time()) ?> -->

<!-- http://t.co/dKP3o1e -->
<meta name="HandheldFriendly" content="True">
<meta name="MobileOptimized" content="320">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0;">  

<!-- For all browsers -->
<link rel="stylesheet" media="screen" href="<?php echo $this->baseUrl('css/style.css?v=1'); ?>">
<link rel="stylesheet" media="print" href="<?php echo $this->baseUrl('css/print.css?v=1'); ?>">
<!-- For progressively larger displays -->
<link rel="stylesheet" media="only screen and (min-width: 480px)" href="<?php echo $this->baseUrl('css/480.css?v=1');?>">
<link rel="stylesheet" media="only screen and (min-width: 768px)" href="<?php echo $this->baseUrl('css/768.css?v=1');?>">
<link rel="stylesheet" media="only screen and (min-width: 992px)" href="<?php echo $this->baseUrl('css/992.css?v=1');?>">
<link rel="stylesheet" media="only screen and (min-width: 1382px)" href="<?php echo $this->baseUrl('css/1382.css?v=1');?>">
<!-- For Retina displays -->
<link rel="stylesheet" media="only screen and (-webkit-min-device-pixel-ratio: 2), only screen and (min-device-pixel-ratio: 2)" href="<?php echo $this->baseUrl('css/2x.css?v=1');?>">

<!--[if (lt IE 9) & (!IEMobile)]>
<link rel="stylesheet" media="screen" href="<?php echo $this->baseUrl('css/480.css?v=1');?>">
<link rel="stylesheet" media="screen" href="<?php echo $this->baseUrl('css/768.css?v=1');?>">
<link rel="stylesheet" media="screen" href="<?php echo $this->baseUrl('css/992.css?v=1');?>">
<![endif]-->

<!-- Scripts -->
<script src="<?php echo $this->baseUrl('js/libs/jquery-1.5.1.min.js');?>"></script>
<script src="<?php echo $this->baseUrl('js/libs/modernizr-custom.js');?>"></script>
<script src="<?php echo $this->baseUrl('js/mylibs/jquery.lightbox-0.5.js');?>"></script>
<script src="<?php echo $this->baseUrl('js/plugins.js');?>"></script>

<!--[if (lt IE 9) & (!IEMobile)]>
<script src="<?php echo $this->baseUrl('js/libs/jquery-extended-selectors.js');?>"></script>
<script src="<?php echo $this->baseUrl('js/libs/selectivizr-min.js');?>"></script>
<script src="<?php echo $this->baseUrl('js/libs/imgsizer.js');?>"></script>
<![endif]-->

<?php if (isset($this->perpage)) : // include per page for catalogue ?>
<script type="text/javascript">
var perpage = <?php echo $this->perpage ?>;
</script>
<?php endif; ?>

<!-- For iPhone 4 -->
<link rel="apple-touch-icon-precomposed" sizes="114x114" href="<?php echo $this->baseUrl('img/h/apple-touch-icon.png');?>">
<!-- For iPad 1-->
<link rel="apple-touch-icon-precomposed" sizes="72x72" href="<?php echo $this->baseUrl('img/m/apple-touch-icon.png');?>">
<!-- For iPhone 3G, iPod Touch and Android -->
<link rel="apple-touch-icon-precomposed" href="<?php echo $this->baseUrl('img/l/apple-touch-icon-precomposed.png');?>">
<!-- For Nokia -->
<link rel="shortcut icon" href="<?php echo $this->baseUrl('img/l/apple-touch-icon.png');?>">
<!-- For everything else -->
<link rel="shortcut icon" href="<?php echo $this->baseUrl('favicon.ico');?>">

<!--iOS. Delete if not required -->
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
<link rel="apple-touch-startup-image" href="<?php echo $this->baseUrl('img/splash.png');?>">

<!--Microsoft. Delete if not required -->
<meta http-equiv="cleartype" content="on">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

<!-- http://t.co/y1jPVnT -->
<link rel="canonical" href="/">


<?php echo $this->headMeta(); ?>
<?php echo $this->headTitle(); ?>
</head>
<body class="clearfix">

<header role="banner" class="clearfix">
<h1><a href="/">Library On-line</a></h1>
<nav class="clearfix">
<ul>
<li><a href="/">Home</a></li>
<li><a href="/">Contact</a></li>
<li><a href="/">Glossary</a></li>
<li><a href="/">Site map</a></li>
<li><a href="/">Help</a></li>
</ul>
<form method="get" action="/search/select" role="search">
<p><input name="q" id="q" type="text" placeholder="Search everything" autocomplete="off" list="search-list"><button>Search</button>
<datalist id="search-list">
<option value="Term1">
<option value="Term2">
<option value="Term3">
<option value="Term4">
<option value="Term5">
</datalist></p>
<p><a href="/advancedsearch/">Advanced search</a></p>
</form>
</nav>
</header>

<?php

// will fix this to work properly with zend nav/router

$organisation_title = (isset($this->organisation)) ? $this->organisation->getTitle() : "";
$series_title = (isset($this->series)) ? $this->series : "";
$document_title = (isset($this->document_title)) ? $this->document_title : "";
$daterange_title = (isset($this->daterange)) ? $this->daterange : "";

$search = array("[orgtitle]", "[seriestitle]", "[doctitle]", "[daterange]");
$replace = array($organisation_title, $series_title, $document_title, $daterange_title);

$breadcrumb = explode("&gt;", $this->navigation()->breadcrumbs()->setLinkLast(false)->setMinDepth(0)->render());

if (!isset($this->nobreadcrumb))
{
	
	if (isset($this->backbutton)) : ?>
	<div class="breadcrumb">
	<p class="backbutton">
	<noscript>&lt; Use the back button in your browser to go back to the previous page</noscript>
	</p>
	</div>
	<?php else : ?>
	<div class="breadcrumb">
	<p><a href="/">Home</a> &gt; 
	<?php echo str_replace($search, $replace, $this->navigation()->breadcrumbs()->setLinkLast(false)->setMinDepth(0)->render()); ?>
	</p>
	</div>
	<?php endif; 
}
?>

<div class="clearfix">



<nav role="navigation">
<ul class="menu">
<li><a href="/report/index.html">User guide to the collection</a></li>
<li><a href="/guides/index.html">Guide to key topics</a></li>
<li><a href="<?php echo $this->baseUrl('browse');?>">Browse material</a>
<?php if ($this->inBrowse) : ?>
<ul>
<li><a href="<?php echo $this->baseUrl('browse/by-contributing-organisation');?>">Organisation</a></li>
<li><a href="<?php echo $this->baseUrl('browse/by-corporate-body');?>">Organisation (list 2)</a></li>
<li><a href="<?php echo $this->baseUrl('browse/by-date');?>">Date</a></li>
<li><a href="<?php echo $this->baseUrl('browse/by-person');?>">Key player</a></li>
<!-- <li><a href="<?php //echo $this->baseUrl('browse/'); ?>">Chapter of the user guide</a></li> -->
<li><a href="<?php echo $this->baseUrl('browse/by-victim-name');?>">Other notible individual</a></li>
<li><a href="<?php echo $this->baseUrl('browse/video');?>">Video</a></li>
<li><a href="<?php echo $this->baseUrl('browse/audio');?>">Audio</a></li>
<li><a href="<?php echo $this->baseUrl('browse/photographs');?>">Photographs</a></li>
</ul>
<?php endif; ?>
</li>

<li><a href="<?php echo $this->baseUrl('catalogue');?>">Catalogue of all material</a></li>
<li><a href="/catalogue-process/index.html">How and why this collection was created</a></li>
<li><a href="/about-panel/index.html">Review team</a></li>
</ul>
</nav>

<div class="content clearfix">
<h1><?php echo $this->escape($this->title); ?></h1>


<?php echo $this->layout()->content; ?>



<div role="complementary">
<?php if ($this->showOrganisationDropdown) : ?>
<form>
<fieldset>
<p class="two-col"><select title="Choose an organisation" id="browseorg" name="browseorg">
<option>Choose organisation:</option>
<option>--------------------</option>
<?php foreach ($this->allOrganisations as $org) : ?>

<option value="<?php echo $org->dir_name ?>"><?php echo $org->owning_organisation ?></option>

<?php endforeach; ?>

</select>
<button type="submit">Go</button>
</p>
</fieldset>
</form>

<?php endif; ?>
<?php if ($this->showReportDownload) : ?>
<div class="action">
<h3><a href="#">User guide</a> <a href="#" class="help" title="Help with PDFs">?</a></h3>
</div>

<?php endif; ?>

<?php if ($this->showDocKey) : ?>
<div class="box">
<ul class="tools">
<li class="options"><b>Show:</b>  
<a href="<?php echo $_SERVER['REQUEST_URI'] ?>" title="50 results">50</a> 
<a href="<?php echo $_SERVER['REQUEST_URI'] ?>" title="50 results">100</a>
<a href="<?php echo $_SERVER['REQUEST_URI'] ?>" title="All results">All</a>
</li>
</ul>
</div>


<div class="box">
<ul class="key">
<li class="key-audio"><abbr>Audio</abbr></li>
<li class="key-camera"><abbr>Image</abbr></li>
<li class="key-doc"><abbr>Page</abbr></li>
<li class="key-pdf"><abbr>PDF</abbr></li>
<li class="key-telly"><abbr>Video</abbr></li>
</ul>
</div>
<?php endif; ?>


</div>


</div>
</div>

<footer role="contentinfo" class="clearfix ihatetimvandamme">

<nav>
<ul>
<li><a href="#">Accessibility</a></li>
<li><a href="#">Privacy policy</a></li>
</ul>
</nav>

<small>&#169; Copyright 2012</small>
</footer>

</body>
</html>