

<h1>Browse the disclosed material</h1>

<div role="main">
<p>'Browse' allows users to look through the material on this website organised in a number of different ways,
for example according to the creation date, or who contributed it.</p>

<ul class="ico-folder">
<li>
<h4><a href="/browse/by-material">Material referenced in the Report</a></h4>
<p><strong>View documents that were used or quoted in the Report.</strong><br/>
Documents are organised by chapter of the Report, eg Chapter 1, Chapter 2, etc.</p>
</li>
</ul>


<h3>All disclosed material</h3>
<p>The categories below allow you to browse all documents disclosed, not just the ones referenced in the Report.</p>
<ul class="ico-folder">
<li>
<h4><a href="/browse/by-contributor">By contributor</a></h4>
<p><strong>View material arranged according to the organisation or individual who supplied it.</strong><br/>
Browse an A-Z list of their names to find material that they have contributed.</p>
</li>

<li>
<h4><a href="/browse/by-person">By person involved</a></h4>
<p><strong>Individuals frequently mentioned in the Report.</strong><br/>
Browse an A-Z list of their names to find documents that refer to them. Does not include those who died.</p>
</li>

  <li>
<h4><a href="/browse/by-corporate-body">By organisation involved</a></h4>
<p><strong>Organisations mentioned in the Report.</strong><br/>
Browse an A-Z list of their names to find documents that refer to them. Includes organisations that did not themselves contribute material to the Panel.</p>
</li>

<li>
<h4><a href="/browse/by-date">By date or date range</a></h4>
<p><strong>Documents that were created during a particular period of time.</strong><br/>
Browse by dates and date ranges such as <strong>before the disaster</strong> and <strong>on the day of the disaster</strong>.</p>
</li>
</ul>
<hr/>
<ul class="ico-folder">
<li>
<h4><a href="/browse/by-name-of-deceased">By name of those who died</a></h4>
<p><strong>Documents that refer to those who died. </strong><br/>
Browse an A-Z list of those who died to find documents that refer to them.</p>
</li>
</ul>

</div>

