<script language="javascript">
function toggleDescription(id)
{
	var obj = document.getElementById(id);
	
	var isVisible = false;
	if (obj.style.display == 'inline')
		isVisible = true;

	if (!isVisible)
	{
		obj.style.display = "inline";
//		document.getElementById(id + "_more").style.display = "none";
		document.getElementById(id + "_link").innerHTML = "less";
	}
	else
	{
		obj.style.display = "none";
//		document.getElementById(id + "_more").style.display = "inline";
		document.getElementById(id + "_link").innerHTML = "more";
	}
}
</script> 
<?php 


function ProcessFormat($oldFormat)
{
	$video_formats = array( 
	   	"vhs tapes",
	   	"video",
	   	"video - umatic",
	   	"video - vhs",
	   	"video cassette (vhs)" );
	
	$audio_formats = array( 
		"audio tapes",
	   	"cassette tape",
	   	"audio",
	   	"audio - cassette",
	   	"audio cassette",
	   	"audio-cassette",
	   	"audio tapes",
	   	"racal tape",	
	   	"cassette audio tape" );
	
	$photo_formats = array ( 
		"photographs",
		"photograph",
		"photographic negative",
		"photographic slide" );

	$standard_formats = array( 
		"item",
		"paper",
		"photocopy",
		"paper;photocopy",
		"paper and objects",
		"paper;photograph",
	   	"coins",
	   	"computer tape",
	   	"floppy disk" );

	$oldFormat = strtolower($oldFormat);
	
	$newFormat = "";
	
	if (in_array($oldFormat, $standard_formats))
		$newFormat = "pdf-icon";
		//$newFormat = "format-pdf";
		
	elseif (in_array($oldFormat, $photo_formats))
		$newFormat = "image-icon";
	elseif (in_array($oldFormat, $video_formats))
		$newFormat = "video-icon";
	elseif (in_array($oldFormat, $audio_formats))
		$newFormat = "audio-icon";
		
	if ($newFormat=="")
	{
		$newFormat = "pdf-icon";
	}
	
	return $newFormat;
}

$foundRecord=false;
?>

<header>
<h1><img alt="" src="<?php echo '/img/ico-folder-open.png' ?>"><?php echo $this->pagetitle ?></h1>
<?php if (isset($this->additionDescription)):?>
	<p><?php echo $this->additionDescription; ?></p>
<?php endif; ?>
<p><?php echo $this->paginationControl($this->paginator, 'sliding', 'pagination_count.phtml'); ?></p>

</header>

<div role="main"> 

<?php 			
//var_dump($this->paginator);
//exit();
?>
  <?php foreach ($this->paginator as $document) : ?>
  
  <?php 
	if (!$foundRecord)
		$foundRecord = true;
		
  	$doctype = ProcessFormat($document['format'])
  ?>  
<article class="result" >  
<header>
      <h1><a href="<?php echo "/repository/" . $document['begin_doc_id'];
					//echo $this->baseUrl('browse/by-contributing-organisation/' . $this->organisation_id . '/' . $this->series . '/' . $document['begin_doc_id']); ?>">
					
        <?php if (empty($document['short_title'])) { echo "Blank title field"; } else { echo $document['short_title']; } ?>
        </a></h1>
      <time><?php echo Hillsborough_Functions::convertDateWithWildcard($document['date_start'], $document['date_start_accuracy']) ?>
        <?php 
        if ($document['date_end'] > 0) 
        { 
        	if ($document['date_start'] > 0) 
        	{ ?>
        		&#8211;
        <?php 
        	} 
        	echo Hillsborough_Functions::convertDateWithWildcard($document['date_end'], $document['date_end_accuracy']); 
        } ?>
      </time>
</header>
	<a href="<?php echo "/repository/" . $document['begin_doc_id']; ?>" class="<?php echo $doctype ?>"></a>
    <?php if (!empty($document['description'])) : ?>
    	<p><?php 
    	$de = substr($document['description'], 0, 200);
    	
    	if (strlen($document['description'])>200)
    	{
    		$de .= "<span style=\"display:none\" id=\"show_".$document['begin_doc_id']."\">".substr($document['description'], 200)."</span>";
    		$de .= "<span style=\"display:inline\" id=\"show_".$document['begin_doc_id']."_more\"> ... </span>";
    		$de .= "<a href=\"javascript:toggleDescription('show_".$document['begin_doc_id']."');\" id=\"show_".$document['begin_doc_id']."_link\">more</a>";
    	}

  	    echo nl2br($de); 
    		
    ?></p>
    <?php endif; ?>

    <footer>
      <ul>
	    <?php if (strpos($_SERVER['REQUEST_URI'], "by-contributor")!=TRUE) : ?>
	        <li><strong>Contributor:</strong> <?php echo $document['owning_organisation'] ?></li>
	    <?php endif; ?>
	    <?php if (!empty($document['archive_ref_id'])) : ?>
	        <li><strong>Contributor reference:</strong> <?php echo $document['archive_ref_id'] ?></li>
	    <?php endif; ?>
        <li><strong>Unique ID:</strong> <?php echo $document['begin_doc_id'] ?></li>
      </ul>
    </footer>

</article>
  
  <?php endforeach; ?>
  <?php if (!$foundRecord):?>
	  <p>No disclosed items found</p>
  <?php endif; ?>
  <?php echo $this->paginationControl($this->paginator, 'sliding', 'pagination.phtml'); ?> </div>
