<h1>Browse material referenced in the Report</h1>

<div role="main">
<p><strong>These are documents that the Panel has quoted or discussed in the Report.</strong></p>
<p>Documents are organised alphabetically by Unique ID under chapter headings (Chapter 1, Chapter 2, etc.).</p>
<p>Please note that whilst there are one or two footnotes in the other parts of the Report, only the 12 chapters in Part 2 directly quote from the disclosed material. </p>

<?php
if ($this->suppressnav != true)
{
	
?>

<br/>
<div class="hentry">
<h3 class="entry-title">Part 2: Hillsborough: What is 'added to public understanding'</h3>
<ul>
	<li><a href="/browse/by-material/s2-p2-c1">Chapter 1: 1981-1989: unheeded warnings, the seeds of disaster</a></li>
	<li><a href="/browse/by-material/s2-p2-c2">Chapter 2: The 'moment' of 1989</a></li>
	<li><a href="/browse/by-material/s2-p2-c3">Chapter 3: Custom, practice, roles, responsibilities</a></li>
	<li><a href="/browse/by-material/s2-p2-c4">Chapter 4: Emergency response and aftermath: 'routinely requested to attend'</a></li>
	<li><a href="/browse/by-material/s2-p2-c5">Chapter 5: Medical evidence: the testimony of the dead</a></li>
	<li><a href="/browse/by-material/s2-p2-c6">Chapter 6: Parallel investigations</a></li>
	<li><a href="/browse/by-material/s2-p2-c7">Chapter 7: Civil Litigation</a></li>
	<li><a href="/browse/by-material/s2-p2-c8">Chapter 8: The Coroner's Inquiry: from the immediate aftermath to the preliminary hearings</a></li>
	<li><a href="/browse/by-material/s2-p2-c9">Chapter 9: The generic hearing, Judicial Review and continuing controversies</a></li>
	<li><a href="/browse/by-material/s2-p2-c10">Chapter 10: The 3.15pm cut-off</a></li>
	<li><a href="/browse/by-material/s2-p2-c11">Chapter 11: Review and alteration of statements</a></li>
	<li><a href="/browse/by-material/s2-p2-c12">Chapter 12: Behind the headlines: the origins, promotion and reproduction of unsubstantiated allegations</a></li>
 </ul>
</div>


<?php
}
?>
</div>